/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wtf_client_Client */

#ifndef _Included_org_wtf_client_Client
#define _Included_org_wtf_client_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wtf_client_Client
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_wtf_client_Client
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client_terminate
  (JNIEnv *, jclass);

/*
 * Class:     org_wtf_client_Client
 * Method:    _create
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client__1create
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client__1destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Client
 * Method:    inner_loop
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wtf_client_Client_inner_1loop
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_open
 * Signature: (Ljava/lang/String;IIII[J)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1open
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jlongArray);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_read
 * Signature: (J[BI)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1read
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_write
 * Signature: (J[BI)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1write
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_getattr
 * Signature: (Ljava/lang/String;Lorg/wtf/client/WTFFileAttrs;)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1getattr
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1rename
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_mkdir
 * Signature: (Ljava/lang/String;I)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1mkdir
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_unlink
 * Signature: (Ljava/lang/String;)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1unlink
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_lseek
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_wtf_client_Client_async_1lseek
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    readdir
 * Signature: (Ljava/lang/String;)Lorg/wtf/client/Iterator;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_readdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wtf_client_Client
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
