/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wtf_client_Client */

#ifndef _Included_org_wtf_client_Client
#define _Included_org_wtf_client_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wtf_client_Client
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_wtf_client_Client
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client_terminate
  (JNIEnv *, jclass);

/*
 * Class:     org_wtf_client_Client
 * Method:    _create
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client__1create
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Client__1destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Client
 * Method:    inner_loop
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wtf_client_Client_inner_1loop
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_open
 * Signature: (Ljava/lang/String;IIII[I)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1open
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_read
 * Signature: (I[BI)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_wtf_client_Client
 * Method:    async_write
 * Signature: (I[BI)Lorg/wtf/client/Deferred;
 */
JNIEXPORT jobject JNICALL Java_org_wtf_client_Client_async_1write
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
