/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wtf_client_Iterator */

#ifndef _Included_org_wtf_client_Iterator
#define _Included_org_wtf_client_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wtf_client_Iterator
 * Method:    _create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Iterator__1create
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Iterator
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Iterator__1destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Iterator
 * Method:    finished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wtf_client_Iterator_finished
  (JNIEnv *, jobject);

/*
 * Class:     org_wtf_client_Iterator
 * Method:    callback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wtf_client_Iterator_callback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
