/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wtf_client_ByteString */

#ifndef _Included_org_wtf_client_ByteString
#define _Included_org_wtf_client_ByteString
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
